---
- name: Add Rook Ceph Helm Repo
  ansible.builtin.shell: |
    helm repo add rook-release https://charts.rook.io/release
    helm repo update
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  run_once: true

- name: Create rook-ceph Namespace and apply PodSecurity labels
  ansible.builtin.shell: |
    /var/lib/rancher/rke2/bin/kubectl create namespace rook-ceph --dry-run=client -o yaml | /var/lib/rancher/rke2/bin/kubectl apply -f -
    /var/lib/rancher/rke2/bin/kubectl label --overwrite ns rook-ceph pod-security.kubernetes.io/enforce=privileged
    /var/lib/rancher/rke2/bin/kubectl label --overwrite ns rook-ceph pod-security.kubernetes.io/audit=privileged
    /var/lib/rancher/rke2/bin/kubectl label --overwrite ns rook-ceph pod-security.kubernetes.io/warn=privileged
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  run_once: true


- name: Deploy Rook Ceph Operator
  ansible.builtin.shell: |
    helm upgrade --install rook-ceph rook-release/rook-ceph \
      --namespace rook-ceph \
      --version v1.13.7 \
      --wait
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  run_once: true

- name: Ensure temp directory exists
  ansible.builtin.file:
    path: /tmp/rook-ceph
    state: directory

- name: Create Ceph Cluster Values File
  ansible.builtin.template:
    src: ceph-cluster-values.yaml.j2
    dest: /tmp/rook-ceph/ceph-cluster-values.yaml
    mode: '0644'
  run_once: true

- name: Deploy Rook Ceph Cluster
  ansible.builtin.shell: |
    helm upgrade --install rook-ceph-cluster rook-release/rook-ceph-cluster \
      --namespace rook-ceph \
      --version v1.13.7 \
      -f /tmp/rook-ceph/ceph-cluster-values.yaml \
      --wait
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  run_once: true

- name: Force restart Ceph Manager Pods to apply custom Dashboard TLS certificate
  ansible.builtin.shell: |
    /var/lib/rancher/rke2/bin/kubectl delete pod -n rook-ceph -l app=rook-ceph-mgr --wait=false || true
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  run_once: true

- name: Create Ceph Dashboard SSL Ingress Config
  ansible.builtin.template:
    src: ceph-dashboard-ingress.yaml.j2
    dest: /tmp/rook-ceph/ceph-dashboard-ingress.yaml
    mode: '0644'
  run_once: true

- name: Delete broken Ceph Dashboard LoadBalancer
  ansible.builtin.shell: |
    /var/lib/rancher/rke2/bin/kubectl delete svc ceph-dashboard-external -n rook-ceph --ignore-not-found
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  run_once: true

- name: Apply Ceph Dashboard Ingress
  ansible.builtin.shell: |
    /var/lib/rancher/rke2/bin/kubectl apply -f /tmp/rook-ceph/ceph-dashboard-ingress.yaml
  environment:
    KUBECONFIG: /etc/rancher/rke2/rke2.yaml
  run_once: true
