---
# Playbook: Add Worker Node
# Usage: ansible-playbook -i inventory.ini add_worker.yml --limit <new_worker_hostname>

- name: Prepare New Worker Node
  hosts: rke2_agents
  become: true
  tags: common
  roles:
    - common

- name: Join New Worker Node to Cluster
  hosts: rke2_agents
  become: true
  tags: join_agent
  roles:
    - rke2_agent

- name: Verify Cluster Worker Status
  hosts: rke2_servers[0]
  become: true
  tasks:
    - name: Check Kubernetes node readiness
      ansible.builtin.shell: /var/lib/rancher/rke2/bin/kubectl get nodes --selector='!node-role.kubernetes.io/master,!node-role.kubernetes.io/control-plane' -o wide
      register: worker_out
      environment:
        KUBECONFIG: /etc/rancher/rke2/rke2.yaml

    - name: Display worker nodes status
      ansible.builtin.debug:
        msg: "{{ worker_out.stdout_lines }}"
