# RKE2 Control Plane (Master Nodes)
[rke2_servers]
master1 ansible_host=192.168.28.120
master2 ansible_host=192.168.28.121
master3 ansible_host=192.168.28.122

# General Worker Nodes (Workloads)
[rke2_agents]
worker1 ansible_host=192.168.28.130
worker2 ansible_host=192.168.28.131
worker3 ansible_host=192.168.28.132

# Dedicated / Co-located Ceph Storage Nodes
[ceph_agents]
worker1 
worker2 
worker3

# Aggregated Kubernetes Cluster Group
[k8s_cluster:children]
rke2_servers
rke2_agents
ceph_agents


