---
- name: Phase 1 - Prepare all nodes
  hosts: all
  become: true
  tags: common
  roles:
    - common

- name: Phase 2 - Initialize first Master
  hosts: rke2_servers[0]
  become: true
  tags: init
  roles:
    - rke2_server_init

- name: Phase 3 - Deploy Kube-VIP (Systemd HA)
  hosts: rke2_servers
  become: true
  tags: vip
  roles:
    - kube_vip

- name: Phase 4 - Join Additional Masters
  hosts: rke2_servers[1:]
  become: true
  serial: 1
  tags: join_server
  roles:
    - rke2_server_join

- name: Phase 5 - Join Worker Nodes
  hosts: rke2_agents
  become: true
  tags: join_agent
  roles:
    - rke2_agent

- name: Phase 6 - Setup Observability (Monitoring & Logging)
  hosts: rke2_servers[0]
  become: true
  tags: monitoring
  roles:
    - monitoring

