---
- name: Prepare all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Deploy RKE2 Servers (Masters)
  hosts: rke2_servers
  become: true
  serial: 1 # Important: Bootstrap one at a time to ensure Etcd quorum / leader election works smoothly
  roles:
    - rke2_server

- name: Deploy RKE2 Agents (Workers)
  hosts: rke2_agents
  become: true
  roles:
    - rke2_agent
